### ISSUE TITLE
adding docstrings

### ISSUE THREAD

**Issue by abdulelahsm** [ARBML/bayanat#3]
Awesome work. I played with the notebook and liked what you've done here. I suggest including docstrings for the methods in Bayanat.py. I can work on that this weekend if you guys need help

**Comment by zaidalyafeai** [comment]
Thus will be helpful. Thanks Abdulelah.

**Comment by zaidalyafeai** [comment]
Thanks @abdulelahsm ! Appreciate your contributions.

**Comment by abdulelahsm** [comment]
@zaidalyafeai sure thing zaid. I appreciate your efforts in democratizing Arabic NLP and I'm always looking to help in any way I can.
